[package]
name = "sutp-demo-client"
version = "0.1.0"
authors = ["Moritz Gunz <moritz.gunz@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
sutp = { path = "../sutp" }
tokio = "0.1.13"
